name: hrss4-test-environment
dependencies:
        - numpy
        - sphinx
        - pytest
        - pytest-pep8
        - pytest-cov
        - flask
        - ipython
        - requests
        - pip:
            - gunicorn
            - pymodm
            - validate_email
            - sendgrid
